version: '3'

services:
  proftpd:
    build:
      context: .
    image: 'ralfherzog/proftpd-docker:latest'
    environment:
      PROFTPD_SERVER_NAME: 'FTP Server'
      PROFTPD_LISTEN_PORT: 21
      PROFTPD_PASSIVE_PORTS: '10010 10012'
      PROFTPD_MASQUERADE_ADDRESS: '1.2.3.4'
      PROFTPD_DYN_MASQ_REFRESH: 28800
      PROFTPD_MAX_INSTANCES: 30
      PROFTPD_LDAP_SERVER: 'ldap.example.com'
      PROFTPD_LDAP_BIND_DN: 'cn=admin,dc=example,dc=com'
      PROFTPD_LDAP_BIND_DN_PASSWORD: 'supersecurepassword'
      PROFTPD_LDAP_USERS: 'dc=users,dc=example,dc=com'
      PROFTPD_LDAP_USERS_FILTER: '(\&(cn=\%v)(objectclass=person))'
      PROFTPD_TLS_ENABLE: 'on'
      PROFTPD_TLS_REQUIRED: 'off'
      PROFTPD_TLS_RSA_CERTIFICATE_FILE: '/etc/ssl/certs/proftpd.crt'
      PROFTPD_TLS_RSA_CERTIFICATE_KEY_FILE: '/etc/ssl/private/proftpd.key'
      PROFTPD_CA_CERTIFICATE_FILE: '/etc/ssl/certs/chain.pem'
    volumes:
    - "./server.crt:/etc/ssl/certs/proftpd.crt:ro"
    - "./server.key:/etc/ssl/private/proftpd.key:ro"
    ports:
    - '21:21'
    - '49152-65534:49152-65534'
